name: Pipeline creado para la cuestión 12 de la práctica.
on:
 workflow_dispatch:
 issues:
  types: [opened,edited]
 project_column: 
  types: [moved]
jobs:
 Prueba:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      
     steps:
      -name: Cache Primes
      uses: actions/cache@v3
       with:
        path: prime-numbers
        key: ${{ runner.os }}-primes
        