name: Pipeline creado para la cuestión 12 de la práctica.
on:
 workflow_dispatch:
 issues:
  types: [opened,edited]
 project_column: 
  types: [moved]
jobs:
 Snake:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Juego snake
        uses: Platane/snk@v2
        