name: Pipeline creado para la cuestión 12 de la práctica.
on:
 workflow_dispatch:
 issues:
  types: [opened,edited]
 project_column: 
  types: [moved]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v3
      with:
        path: prime-numbers
        key: ${{ runner.os }}-primes
